### ISSUE TITLE
release?

### ISSUE THREAD

**Issue by scottlamb** [sdroege/rtsp-types#13]
I'm working on a high-level RTSP crate (https://github.com/scottlamb/retina) built on rtsp-types. I'd like to make a first release to crates.io soon, which requires using crates.io versions of all dependencies. Could you make a new rtsp-types release please? I need the recent fixes. Thanks!

**Comment by sdroege** [comment]
Sure, I'll try to get a release out over the weekend. Btw: https://github.com/sdroege/rtsp-server

**Comment by sdroege** [comment]
Done, also `sdp-types` :)

**Comment by scottlamb** [comment]
Thank you!

> Btw: https://github.com/sdroege/rtsp-server

I peeked at that a while back. I think the two are quite different: server vs (at least initially) client focus, RTSP/2.0 vs RTSP/1.0, async-std vs (currently) tokio, an example that uses gstreamer vs pure Rust codec depacketization, etc.

**Comment by sdroege** [comment]
> RTSP/2.0 vs RTSP/1.0

Which one are you targetting? My server code is targetting RTSP 2.0 but will have a compat mode for RTSP 1.0.

> async-std vs (currently) tokio

Goal is to make it use either of the two, and right now that would be quite easy to achieve :)

> an example that uses gstreamer vs pure Rust codec depacketization, etc.

Yeah for simplicity but there won't be any mandatory GStreamer dependency.

**Comment by scottlamb** [comment]
I'm targeting RTSP/1.0 because that's what ONVIF IP surveillance cameras use.

**Comment by sdroege** [comment]
Ah that makes sense. ONVIF also has a couple of strange modes though
and was generally a bit annoying to implement in GStreamer :)

**Comment by scottlamb** [comment]
Oh, I see now that you added ONVIF backchannel support to GStreamer. Neat. I haven't added an equivalent of that to my crate yet. IMHO the most annoying thing is not what's in the spec but that the cameras I'm using don't ever implement any spec correctly. Eg their timestamps are [garbage](https://forum.videolan.org/viewtopic.php?f=2&t=157388).

**Comment by sdroege** [comment]
Yes, that's the other problem :)
