### ISSUE TITLE
Bump version

### ISSUE THREAD

**Issue by r4v3n6101** [sdroege/rtsp-types#21]
Hi! In a nutshell, I guess we could bump the crate version because they're contain some changes that could be fetched up by end-users.

**Comment by sdroege** [comment]
You mean you'd like to have a new release on crates.io? I can take care of that some time later today or tomorrow

**Comment by r4v3n6101** [comment]
Yeah, i mean that. Thanks!

**Comment by sdroege** [comment]
Done
