### ISSUE TITLE
compile error: error[E0432]: unresolved import `tinyvec::TinyVec`

### ISSUE THREAD

**Issue by tubzby** [sdroege/rtsp-types#26]
Seems that `tinyvec` has disabled the default feature 'alloc' which disabled `tinyvec::TinyVec`.

**Comment by sdroege** [comment]
"Nice" :) Do you want to provide a PR for enabling the `alloc` feature of `tinyvec` in the `Cargo.toml` here?

**Comment by tubzby** [comment]
Of course.
