### ISSUE TITLE
Content-Length with the string sensitive case issue

### ISSUE THREAD

**Issue by qianzhang5** [sdroege/rtsp-types#7]
Hi @sdroege , The body() in parser.rs may miss some cases that "Content-Length:"  has up or lowercase. It would be better that find(|h| h.name == "Content-Length") is implemented in case insensitive comparing.  
BTW, It would be nicer that Message includes "Annnounce" type  that is a standard method in RTPS/1.0.  Thanks!

**Comment by qianzhang5** [comment]
Besides Announce, another type "Record" is missing.  following are all request types in RFC2326. 
Request-Line = Method SP Request-URI SP RTSP-Version CRLF

   Method         =         "DESCRIBE"              ; Section 10.2
                  |         "ANNOUNCE"              ; Section 10.3
                  |         "GET_PARAMETER"         ; Section 10.8
                  |         "OPTIONS"               ; Section 10.1
                  |         "PAUSE"                 ; Section 10.6
                  |         "PLAY"                  ; Section 10.5
                  |         "RECORD"                ; Section 10.11
                  |         "REDIRECT"              ; Section 10.10
                  |         "SETUP"                 ; Section 10.4
                  |         "SET_PARAMETER"         ; Section 10.9
                  |         "TEARDOWN"              ; Section 10.7
                  |         extension-method

**Comment by sdroege** [comment]
> Hi @sdroege , The body() in parser.rs may miss some cases that "Content-Length:" has up or lowercase. It would be better that find(|h| h.name == "Content-Length") is implemented in case insensitive comparing.

Yes, header names are indeed case insensitive. Do you want to submit a PR for this?

>  BTW, It would be nicer that Message includes "Annnounce" type that is a standard method in RTPS/1.0. Thanks!

And also `Record` :) Feel free to send a PR to add it to the method type.

**Comment by qianzhang5** [comment]
I want to submit a PR for this. how to?
